version: "3.7"

services:

  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: service1
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
#      - ./user_db.sql:/docker-entrypoint-initdb.d/user_db.sql
#      - ./user_db.sql:/user_db.sql
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      retries: 5
      timeout: 3s
    env_file:
      - .env

  web:
    build:
      context: .
    container_name: fastapi_app
    command: commands/app.sh
    ports:
      - 8080:8000
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

  alembic:
    build:
      context: .
    container_name: alembic_migrations_db
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
    command: commands/alembic.sh

  tests:
    build:
      context: .
    container_name: tests_db
    depends_on:
      - web
      - alembic
    command: commands/tests.sh


volumes:
  pgdata:









