"""add test_column

Revision ID: 8e806cd249aa
Revises: cdad032fc08f
Create Date: 2023-10-02 16:13:15.643823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e806cd249aa'
down_revision: Union[str, None] = 'cdad032fc08f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_test', sa.Column('test_columns', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_test', 'test_columns')
    # ### end Alembic commands ###
